### ISSUE TITLE
nonHeapMemMax vs XX:MaxMetaspaceSize

### ISSUE THREAD

**Issue by victorbrca** [FollettSchoolSolutions/perfmon4j#23]
Hello,

We have our JVM running with `XX:MaxMetaspaceSize` set to '1024m', however, when looking at 'perfmon4j.log' we see the following values: 

```
 nonHeapMemUsed........... 543.655 MB
 nonHeapMemCommitted...... 578.012 MB
 nonHeapMemMax............ 2280.000 MB
 nonHeapMemUsedCommitted.. 94.056%
 nonHeapMemUsedMax........ 23.845%
```

We are concerned with the size of ` nonHeapMemMax` and that it seems to not be honoring the value set in `XX:MaxMetaspaceSize`. Or do we have a wrong understanding on this? 

Thanks in advance for any comments.

**Comment by ddeuchert** [comment]
Perfmon4j retrieves those values directly from the Java Virtual Machine through the java.lang.management.MemoryMXBean.  See: https://docs.oracle.com/javase/10/docs/api/java/lang/management/MemoryMXBean.html

That monitor has not been updated in a while.  What version of java are you using?  Perfmon4j may need a patch to handle the MetaspaceSize settings correctly.

Thanks,

Dave

**Comment by victorbrca** [comment]
Thanks for the reply and my apologies for the late follow up. 

This looks like is working as expected. The value of `-XX:MaxMetaspaceSize` is just an upper limit and it can grow up to 230% of the specified size.
